package com.examly.springapp.model;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
@Entity //Map the class with the database
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PropertyInquiry {
@Id //Primary key 
@GeneratedValue(strategy= GenerationType.IDENTITY) //AutoGenerated ID
private long inquiryId;
@ManyToOne // Establishes a many-to-one relationship with the User entity
@JoinColumn(name = "userId", nullable=false)
private User user;
@ManyToOne  // Establishes a many-to-one relationship with the Property Entity
@JoinColumn(name = "propertyId", nullable=false) //Setting the name of the foreign Key
private Property property;
private String message;
private String priority;
private String status;
private LocalDate inquiryDate;
private LocalDate responseDate;
private String adminResponse;
private String contactDetails;
}
