package com.examly.springapp.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;

@Entity  // Map the class with the database
public class User {

    @Id // Primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // AutoGenerated ID
    private long userId;

    @Column(unique=true) // Ensure the email is unique
    @Email(message = "Email should be valid") // Validate format of email
    @NotBlank(message = "Email is mandatory") // Ensure email is not blank
    private String email;

    @NotBlank(message = "Password is mandatory") // Ensure password is not blank
    @Size(min = 8, message = "Password must be at least 8 characters long") // Validate password length
    private String password;

    @NotBlank(message = "Username is mandatory") // Ensure username is not blank
    private String username;

    //@Pattern(regexp = "^[0-9]{10}$", message = "Mobile number must be 10 digits") // Validate mobile number format
    private String mobileNumber;

    @NotBlank(message = "User role is mandatory") // Ensure user role is not blank
    private String userRole;

    // Generate Getters and Setters
    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getUserRole() {
        return userRole;
    }

    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }
}
