package com.examly.springapp.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity  // Map the class with the database
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id // Primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // AutoGenerated ID
    private long userId;

    @Column(unique=true) // Ensure the email is unique
    @Email(message = "Email should be valid") // Validate format of email
    @NotBlank(message = "Email is mandatory") // Ensure email is not blank
    private String email;

    @NotBlank(message = "Password is mandatory") // Ensure password is not blank
    @Size(min = 8, message = "Password must be at least 8 characters long") // Validate password length
    private String password;

    @NotBlank(message = "Username is mandatory") // Ensure username is not blank
    private String username;

    //@Pattern(regexp = "^[0-9]{10}$", message = "Mobile number must be 10 digits") // Validate mobile number format
    private String mobileNumber;

    @NotBlank(message = "User role is mandatory") // Ensure user role is not blank
    private String userRole;

}