package com.examly.springapp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity  //Map the class with the database
public class User {
@Id //Primary key 
@GeneratedValue(strategy = GenerationType.IDENTITY)  //AutoGenerated ID
private long userId;
@Column(unique=true) //For unique column email should be unique always
private String email;
private String  password;
private String username;
private String mobileNumber;
private String userRole;
//Generate Getters and Setters
public long getUserId() {
    return userId;
}
public void setUserId(long userId) {
    this.userId = userId;
}
public String getEmail() {
    return email;
}
public void setEmail(String email) {
    this.email = email;
}
public String getPassword() {
    return password;
}
public void setPassword(String password) {
    this.password = password;
}
public String getUsername() {
    return username;
}
public void setUsername(String username) {
    this.username = username;
}
public String getMobileNumber() {
    return mobileNumber;
}
public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
}
public String getUserRole() {
    return userRole;
}
public void setUserRole(String userRole) {
    this.userRole = userRole;
}


}
